#!/bin/bash

#
# Preparation
#
cd $HOME
sudo apt-get update

#
# Install Node.js
#
echo "Installing Node.js"

# Install a special package
sudo apt-get install -y python-software-properties python g++ make

# Add a new repository for apt-get to search
sudo add-apt-repository ppa:chris-lea/node.js

# Update apt-get’s knowledge of which packages are where
sudo apt-get update

# Now install nodejs and npm
sudo apt-get install -y nodejs

#
# Install git
#
echo "Installing git"
sudo apt-get install -y git-core 
 
#
# Install latest git, emacs, jshint, heroku tools and dotfiles 
#
echo "Installing latest emacs"
git clone https://github.com/startup-class/setup.git ./tmp/setup
./tmp/setup/setup.sh
rm -rf ./tmp/setup

#
# Install express
#
sudo npm install express-generator -g

#
# Install redis
#
sudo apt-get install tk8.5
wget http://download.redis.io/redis-stable.tar.gz
tar xvzf redis-stable.tar.gz
pushd redis-stable
sudo make install
sudo mkdir /etc/redis
sudo mkdir /var/redis
sudo cp utils/redis_init_script /etc/init.d/redis_6379
sudo cp redis.conf /etc/redis/6379.conf
sudo mkdir /var/redis/6379
sudo sed -i 's/redis.pid/redis_6379.pid/g' /etc/redis/6379.conf
sudo sed -i 's/daemonize no/daemonize yes/g' /etc/redis/6379.conf
sudo sed -i 's/logfile \"\"/logfile \"\/var\/log\/redis_6379.log\"/g' /etc/redis/6379.conf
sudo sed -i 's/dir .\//dir "\/var\/redis\/6379\"/g' /etc/redis/6379.conf
sudo update-rc.d redis_6379 defaults 
popd
